"""empty message

Revision ID: 1e43a0935f6d
Revises: 
Create Date: 2023-06-06 22:47:39.066035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e43a0935f6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('bookings')
    op.drop_table('comments')
    op.drop_table('cookuser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cookuser',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=80), nullable=True),
    sa.Column('phonenumber', sa.VARCHAR(length=12), nullable=True),
    sa.Column('email', sa.VARCHAR(length=40), nullable=True),
    sa.Column('password', sa.VARCHAR(length=64), nullable=True),
    sa.Column('userid', sa.VARCHAR(length=32), nullable=True),
    sa.Column('username', sa.VARCHAR(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=400), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('event_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['cookuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order', sa.VARCHAR(length=64), nullable=True),
    sa.Column('userid', sa.VARCHAR(length=100), nullable=True),
    sa.Column('booked_eventid', sa.INTEGER(), nullable=True),
    sa.Column('booked_student', sa.INTEGER(), nullable=False),
    sa.Column('booked_concession', sa.INTEGER(), nullable=False),
    sa.Column('booked_postgraduate', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['booked_eventid'], ['events.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['cookuser.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('order')
    )
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('time', sa.TIME(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=100), nullable=False),
    sa.Column('states', sa.VARCHAR(length=100), nullable=False),
    sa.Column('image', sa.VARCHAR(length=255), nullable=True),
    sa.Column('postgraduate', sa.INTEGER(), nullable=False),
    sa.Column('student', sa.INTEGER(), nullable=False),
    sa.Column('concession', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), nullable=False),
    sa.Column('status', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
